# Generated by Django 4.1.7 on 2023-03-16 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='propertyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('constructionyear', models.DateField()),
                ('buildrname', models.CharField(max_length=50)),
                ('rera', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'propertyDetail',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'propertyType',
            },
        ),
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rent', models.BooleanField(default=True)),
                ('propertyDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.propertydetail')),
            ],
        ),
    ]
